name: dart_mqtt_broker
description: MQTT Broker server app.
version: 1.0.0
repository: https://github.com/mskayali/dart_mqtt_broker

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
